/*You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

*/
/*Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.*/
//sol1
class Solution {
public:
    char findTheDifference(string s, string t) {
    //    vector<char>mp1;
    //    vector<char>mp2;
    //    for(int i=0;i<s.length();i++)
    //    {
    //        mp1.push_back(s[i]);
    //    }
    //    for(int i=0;i<t.length();i++)
    //    {
    //        mp2.push_back(t[i]);
    //    }
    //    sort(mp1.begin(),mp1.end());
    //    sort(mp2.begin(),mp2.end());
    //    int i=0,j=0;
    //    while(i<s.length())
    //    {
    //        if(mp1[i]==mp2[j])
    //        {
    //            i++;
    //            j++;
    //            continue;
    //        }
    //        else
    //        {
    //            return mp2[j];
    //        }
    //    }
    //    return mp2[j];
    //sol2
    sort(s.begin(),s.end());
    sort(t.begin(),t.end());
    int i=0,j=0;
       while(i<s.length())
       {
           if(s[i]==t[j])
           {
               i++;
               j++;
               continue;
           }
           else
           {
               return t[j];
           }
       }
       return t[j];


    }
};